apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghtjd22103/django-image-deployment
spec:
  selector:
    matchLabels:
      app: ghtjd22103/django-image
  replicas: 4
  template:
    metadata:
      labels:
        app: ghtjd22103/django-image
    spec:
      containers:
      - name: ghtjd22103/django-image
        image: ghtjd22103/django-image:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
